records = {
    [3773] = {name='Besieged Participation (M)',parent='Other',category='Monthly Objectives',},
    [3774] = {name='Campaign Participation (M)',parent='Other',category='Monthly Objectives',},
    [3000] = {name='Unity Communique A (UC)',parent='Unity', category='Unity (Shared A)',},
    [3001] = {name='Home Point Comrade A (UC)',parent='Unity', category='Unity (Shared A)',},
    [3002] = {name='Vanquish Multiple Enemies  A (UC)',parent='Unity', category='Unity (Shared A)',},
    [3055] = {name='Van. Enemies w. Unity Leader A (UC)',parent='Unity', category='Unity (Shared A)',},
    [3009] = {name='Unity Communique B (UC)',parent='Unity', category='Unity (Shared B)',},
    [3011] = {name='Vanquish Multiple Enemies B (UC)',parent='Unity', category='Unity (Shared B)',},
    [3056] = {name='Van. Enemies w. Unity Leader B (UC)',parent='Unity', category='Unity (Shared B)',},
    [3018] = {name='Unity Communique C (UC)',parent='Unity', category='Unity (Shared C)',},
    [3019] = {name='Home Point Comrade C (UC)',parent='Unity', category='Unity (Shared C)',},
    [3020] = {name='Vanquish Multiple Enemies C (UC)',parent='Unity', category='Unity (Shared C)',},
    [3057] = {name='Van. Enemies w. Unity Leader C (UC)',parent='Unity', category='Unity (Shared C)',},
    [3027] = {name='Unity Communique D (UC)',parent='Unity', category='Unity (Shared D)',},
    [3029] = {name='Vanquish Multiple Enemies D (UC)',parent='Unity', category='Unity (Shared D)',},
    [3058] = {name='Van. Enemies w. Unity Leader D (UC)',parent='Unity', category='Unity (Shared D)',},
    [3036] = {name='Unity Communique E (UC)',parent='Unity', category='Unity (Shared E)',},
    [3037] = {name='Home Point Comrade E (UC)',parent='Unity', category='Unity (Shared E)',},
    [3038] = {name='Vanquish Multiple Enemies E (UC)',parent='Unity', category='Unity (Shared E)',},
    [3059] = {name='Van. Enemies w. Unity Leader E (UC)',parent='Unity', category='Unity (Shared E)',},
    [3045] = {name='Unity Communique F (UC)',parent='Unity', category='Unity (Shared F)',},
    [3047] = {name='Vanquish Multiple Enemies F (UC)',parent='Unity', category='Unity (Shared F)',},
    [3060] = {name='Van. Enemies w. Unity Leader F (UC)',parent='Unity', category='Unity (Shared F)',},
    [3363] = {name='Gastro-revolution (W)',parent='Vana\'versary',shorts={'gastro1','grape'},},   -- eggs/grape
    [3371] = {name='Gastro-revolution 2 (W)',parent='Vana\'versary',shorts={'gastro2','apple'},}, -- apple pie
    [3381] = {name='Gastro-Revolution 3 (W)',parent='Vana\'versary',shorts={'gastro3','shroom',},}, -- roast mushroom
    [3390] = {name='Gastro-Revolution 4 (W)',parent='Vana\'versary',shorts={'gastro4','ginger',},}, -- ginger cookies
    [3367] = {name='Signet, brb (W)',parent='15th Vana\'versary I',shorts={'signet'},},
    [3374] = {name='Colorless (W)',parent='Vana\'versary',shorts={'tele','xtal',},},           -- telepoint xtal
    [3380] = {name='Sit (W)',parent='Vana\'versary',shorts={'sit',},},
    [3393] = {name='Auction House Blues (W)',parent='Vana\'versary',shorts={'besiegedw',},}, -- besieged
}

-- id to name mapping
roe_id_keys = {
    -- 'Basics'
    [1] = 'First Step Forward',
    [2] = 'Vanquish One Enemy',
    [3] = 'Undertake a FoV Training Regime',
    [4] = 'Heal Without Using Magic',
    [5] = 'All for One',
    [11] = 'Undertake a GoV Training Regime',
    [499] = 'Stepping into an Ambuscade',
    [932] = 'Call Forth an Alter Ego',  -- gives Cipher: Valaineral
    [933] = 'Alter Ego: Valaineral',    -- gives Cipher: Mihli
    [934] = 'Alter Ego: Mihli Aliapoh', -- gives Cipher: Tenzen
    [935] = 'Alter Ego: Tenzen',        -- gives Cipher: Adelheid
    [936] = 'Alter Ego: Adelheid',      -- gives Cipher: Joachim
    [937] = 'Alter Ego: Joachim',
    [1447] = 'Exploring the Trove',
    [1448] = 'Assist Channel',  -- unset works, but set does not work
    -- 'Intermediate'
    [1045] = 'Achieve Level 99',        -- gives Kupon A-PK109 x5
    [1046] = 'An Eminent Scholar',          -- gives Kupon W-EMI
    [1047] = 'An Eminent Scholar 2',        -- gives Kupon A-EMI
    [1048] = 'An Eminent Scholar 3',        -- 
    [1049] = 'Always Stand on 117',         -- gives Cipher: Koru-Moru
    [1050] = 'Taming the Wilds',
    [1057] = 'Skirmisher: Rala Waterways',
    [1058] = 'Skirmisher: Cirdas Caverns',
    [1059] = 'Skirmisher: Yorcia Weald',
    [1054] = 'Repelling an Ambuscade',
    [1055] = 'Artifact Reforger',
    [1056] = 'Artifact Reforger 2',
    [1051] = 'A. Skirmisher: Rala Waterways',
    [1052] = 'A. Skirmisher: Cirdas Caverns',
    [1053] = 'A. Skirmisher: Yorcia Weald',
    -- 'Synthesis'
    [100] = 'Speak to Carpenters\' Guild Master',
    [101] = 'Speak to Blacksmiths\' Guild Master',
    [102] = 'Speak to Goldsmiths\' Guild Master',
    [103] = 'Speak to Weavers\' Guild Master',
    [104] = 'Speak to Tanners\' Guild Master',
    [105] = 'Speak to Boneworkers\' Guild Master',
    [106] = 'Speak to Alchemists\' Guild Master',
    [107] = 'Speak to Culinarians\' Guild Master',
    [108] = 'Woodworking: Padded Box',
    [109] = 'Smithing: Bronze Knife',
    [110] = 'Goldsmithing: Copper Ring',
    [111] = 'Weaving: Headgear',
    [112] = 'Tanning: Leather Bandana',
    [113] = 'Boneworking: Shell Powder',
    [114] = 'Alchemy: Black Ink',
    [115] = 'Cooking: Pebble Soup',
    -- 'Quests 1'
    [500] = 'Mog House Exit: San d\'Oria',
    [501] = 'Mog House Exit: Bastok',
    [502] = 'Mog House Exit: Windurst',
    [503] = 'Mog House Exit: Jeuno',
    [504] = 'Mog House Exit: Aht Urhgan',
    [505] = 'Obtain a Support Job',
    [506] = 'Obtain an Alter Ego: San d\'Oria',
    [507] = 'Obtain an Alter Ego: Bastok',
    [508] = 'Obtain an Alter Ego: Windurst',
    [509] = 'Obtain a Chocobo License',
    [510] = 'Obtain Job: Paladin',
    [511] = 'Obtain Job: Dark Knight',
    [512] = 'Obtain Job: Beastmaster',
    [513] = 'Obtain Job: Bard',
    [514] = 'Obtain Job: Ranger',
    [515] = 'Obtain Job: Samurai',
    [516] = 'Obtain Job: Ninja',
    [517] = 'Obtain Job:Dragoon',
    [518] = 'Obtain Job: Summoner',
    [519] = 'Obtain Job: Blue Mage',
    [520] = 'Obtain Job: Corsair',
    [521] = 'Obtain Job: Puppetmaster',
    [522] = 'Obtain Job: Dancer',
    [523] = 'Obtain Job: Scholar',
    [524] = 'Obtain Job: Geomancer',
    [525] = 'Obtain Job: Rune Fencer',
    -- 'Quests (Artifact 1)'
    [629] = 'WAR Artifact Quest I',
    [630] = 'WAR Artifact Quest II',
    [631] = 'WAR Artifact Quest III',
    [632] = 'MNK Artifact Quest I',
    [633] = 'MNK Artifact Quest II',
    [634] = 'MNK Artifact Quest III',
    [635] = 'WHM Artifact Quest I',
    [636] = 'WHM Artifact Quest II',
    [637] = 'WHM Artifact Quest III',
    [638] = 'BLM Artifact Quest I',
    [639] = 'BLM Artifact Quest II',
    [640] = 'BLM Artifact Quest III',
    [641] = 'RDM Artifact Quest I',
    [642] = 'RDM Artifact Quest II',
    [643] = 'RDM Artifact Quest III',
    [644] = 'THF Artifact Quest I',
    [645] = 'THF Artifact Quest II',
    [646] = 'THF Artifact Quest III',
    [647] = 'PLD Artifact Quest I',
    [648] = 'PLD Artifact Quest II',
    [649] = 'PLD Artifact Quest III',
    [650] = 'DRK Artifact Quest I',
    [651] = 'DRK Artifact Quest II',
    [652] = 'DRK Artifact Quest III',
    [653] = 'BST Artifact Quest I',
    [654] = 'BST Artifact Quest II',
    [655] = 'BST Artifact Quest III',
    -- 'Quests (Artifact 2)'
    [656] = 'BRD Artifact Quest I',
    [657] = 'BRD Artifact Quest II',
    [658] = 'BRD Artifact Quest III',
    [659] = 'RNG Artifact Quest I',
    [660] = 'RNG Artifact Quest II',
    [661] = 'RNG Artifact Quest III',
    [662] = 'SAM Artifact Quest I',
    [663] = 'SAM Artifact Quest II',
    [664] = 'SAM Artifact Quest III',
    [665] = 'Nin Artifact Quest I',
    [666] = 'NIN Artifact Quest II',
    [667] = 'NIN Artifact Quest III',
    [668] = 'DRG Artifact Quest I',
    [669] = 'DRG Artifact Quest II',
    [670] = 'DRG Artifact Quest III',
    [671] = 'SMN Artifact Quest I',
    [672] = 'SMN Artifact Quest II',
    [673] = 'SMN Artifact Quest III',
    [674] = 'BLU Artifact Quest I',
    [675] = 'BLU Artifact Quest II',
    [676] = 'BLU Artifact Quest III',
    [677] = 'COR Artifact Quest I',
    [678] = 'COR Artifact Quest II',
    [679] = 'COR Artifact Quest III',
    [680] = 'PUP Artifact Quest I',
    [681] = 'PUP Artifact Quest II',
    [682] = 'PUP Artifact Quest III',
    -- 'Quests (Artifact 3)'
    [683] = 'DNC Artifact Quest I',
    [684] = 'DNC Artifact Quest II',
    [685] = 'DNC Artifact Quest III',
    [686] = 'SCH Artifact Quest I',
    [687] = 'SCH Artifact Quest II',
    [688] = 'SCH Artifact Quest III',
    [689] = 'GEO Artifact Quest I',
    [690] = 'GEO Artifact Quest II',
    [691] = 'GEO Artifact Quest III',
    [692] = 'RUN Artifact Quest I',
    [693] = 'RUN Artifact Quest II',
    [694] = 'RUN Artifact Quest III',
    -- 'Level Cap Increase'
    [705] = 'Level Cap Increase: 55',
    [706] = 'Level Cap Increase: 60',
    [707] = 'Level Cap Increase: 65',
    [708] = 'Level Cap Increase: 70',
    [709] = 'Level Cap Increase: 75',
    [710] = 'Level Cap Increase: 80',
    [711] = 'Level Cap Increase: 85',
    [712] = 'Level Cap Increase: 90',
    [713] = 'Level Cap Increase: 95',
    [714] = 'Level Cap Increase: 99',
    [871] = 'Level Cap Increase: 75 (BLU)',
    [872] = 'Level Cap Increase: 75 (COR)',
    [873] = 'Level Cap Increase: 75 (PUP)',
    [874] = 'Level Cap Increase: 75 (DNC)',
    [875] = 'Level Cap Increase: 75 (SCH)',
    [876] = 'Level Cap Increase: 75 (GEO)',
    [877] = 'Level Cap Increase: 75 (RUN)',
    -- 'Storage Expansion'
    [715] = 'Inventory Expansion 35',
    [716] = 'Inventory Expansion 40',
    [717] = 'Inventory Expansion 45',
    [718] = 'Inventory Expansion 50',
    [719] = 'Inventory Expansion 55',
    [720] = 'Inventory Expansion 60',
    [721] = 'Inventory Expansion 65',
    [722] = 'Inventory Expansion 70',
    [723] = 'Inventory Expansion 75',
    [724] = 'Inventory Expansion 80',
    [939] = 'Mog Safe Expansion: 60',
    [940] = 'Mog Safe Expansion: 70',
    [941] = 'Mog Safe Expansion: 80',
    -- 'Quests (Weapon Skills)'
    [839] = 'Asuran Fists',
    [840] = 'Evisceration',
    [841] = 'Savage Blade',
    [842] = 'Ground Strike',
    [843] = 'Decimation',
    [844] = 'Steel Cyclone',
    [845] = 'Spiral Hell',
    [846] = 'Impulse Drive',
    [847] = 'Blade: Ku',
    [848] = 'Tachi: Kasha',
    [849] = 'Black Halo',
    [850] = 'Retribution',
    [851] = 'Empyreal Arrow',
    [852] = 'Detonator',
    --'Missions (Rhapsodies of Vana\'diel)'
    [1373] = 'Rhapsodies of Vana\'diel Chapter 1-1',
    [1374] = 'Rhapsodies of Vana\'diel Chapter 1-2',
    [1375] = 'Rhapsodies of Vana\'diel Chapter 1-3',
    [1416] = 'Rhapsodies of Vana\'diel Chapter 2-1',
    [1417] = 'Rhapsodies of Vana\'diel Chapter 2-2',
    [1418] = 'Rhapsodies of Vana\'diel Chapter 2-3',
    [1419] = 'Rhapsodies of Vana\'diel Chapter 2-4',
    [1420] = 'Rhapsodies of Vana\'diel Chapter 2-5',
    [1421] = 'Rhapsodies of Vana\'diel Chapter 2-6',
    [1422] = 'Rhapsodies of Vana\'diel Chapter 2-7',
    [1423] = 'Rhapsodies of Vana\'diel Chapter 2-8',
    [1424] = 'Rhapsodies of Vana\'diel Chapter 2-9',
    [1432] = 'Rhapsodies of Vana\'diel Chapter 3-1',
    [1433] = 'Rhapsodies of Vana\'diel Chapter 3-2',
    [1434] = 'Rhapsodies of Vana\'diel Chapter 3-3',
    [1435] = 'Rhapsodies of Vana\'diel Chapter 3-4',
    [1436] = 'Rhapsodies of Vana\'diel Chapter 3-5',
    [1437] = 'Rhapsodies of Vana\'diel Chapter 3-6',
    [1438] = 'Rhapsodies of Vana\'diel Chapter 3-7',
    [1439] = 'Rhapsodies of Vana\'diel Chapter 3-8',
    [1440] = 'Rhapsodies of Vana\'diel Chapter 3-9',
    [1441] = 'Rhapsodies of Vana\'diel Chapter 3-10',
    [1442] = 'Rhapsodies of Vana\'diel Chapter 3-11',
    [1443] = 'Rhapsodies of Vana\'diel Chapter 3-12',
    -- 'Missions (San d\'Oria)'
    [1313] = 'San d\'Oria Rank 1-1',
    [1314] = 'San d\'Oria Rank 1-2',
    [1315] = 'San d\'Oria Rank 1-3',
    [1316] = 'San d\'Oria Rank 2-1',
    [1317] = 'San d\'Oria Rank 2-2',
    [1318] = 'San d\'Oria Rank 2-3',
    [1319] = 'San d\'Oria Rank 3-1',
    [1320] = 'San d\'Oria Rank 3-2',
    [1321] = 'San d\'Oria Rank 3-3',
    [1322] = 'San d\'Oria Rank 4',
    [1323] = 'San d\'Oria Rank 5-1',
    [1324] = 'San d\'Oria Rank 5-2',
    [1325] = 'San d\'Oria Rank 6-1',
    [1326] = 'San d\'Oria Rank 6-2',
    [1327] = 'San d\'Oria Rank 7-1',
    [1328] = 'San d\'Oria Rank 7-2',
    [1329] = 'San d\'Oria Rank 8-1',
    [1330] = 'San d\'Oria Rank 8-2',
    [1331] = 'San d\'Oria Rank 9-1',
    [1332] = 'San d\'Oria Rank 9-2',
    -- 'Missions (Bastok)'
    [1333] = 'Bastok Rank 1-1',
    [1334] = 'Bastok Rank 1-2',
    [1335] = 'Bastok Rank 1-3',
    [1336] = 'Bastok Rank 2-1',
    [1337] = 'Bastok Rank 2-2',
    [1338] = 'Bastok Rank 2-3',
    [1339] = 'Bastok Rank 3-1',
    [1340] = 'Bastok Rank 3-2',
    [1341] = 'Bastok Rank 3-3',
    [1342] = 'Bastok Rank 4',
    [1343] = 'Bastok Rank 5-1',
    [1344] = 'Bastok Rank 5-2',
    [1345] = 'Bastok Rank 6-1',
    [1346] = 'Bastok Rank 6-2',
    [1347] = 'Bastok Rank 7-1',
    [1348] = 'Bastok Rank 7-2',
    [1349] = 'Bastok Rank 8-1',
    [1350] = 'Bastok Rank 8-2',
    [1351] = 'Bastok Rank 9-1',
    [1352] = 'Bastok Rank 9-2',
    -- 'Missions (Windurst)'
    [1353] = 'Windurst Rank 1-1',
    [1354] = 'Windurst Rank 1-2',
    [1355] = 'Windurst Rank 1-3',
    [1356] = 'Windurst Rank 2-1',
    [1357] = 'Windurst Rank 2-2',
    [1358] = 'Windurst Rank 2-3',
    [1359] = 'Windurst Rank 3-1',
    [1360] = 'Windurst Rank 3-2',
    [1361] = 'Windurst Rank 3-3',
    [1362] = 'Windurst Rank 4',
    [1363] = 'Windurst Rank 5-1',
    [1364] = 'Windurst Rank 5-2',
    [1365] = 'Windurst Rank 6-1',
    [1366] = 'Windurst Rank 6-2',
    [1367] = 'Windurst Rank 7-1',
    [1368] = 'Windurst Rank 7-2',
    [1369] = 'Windurst Rank 8-1',
    [1370] = 'Windurst Rank 8-2',
    [1371] = 'Windurst Rank 9-1',
    [1372] = 'Windurst Rank 9-2',
    -- 'Missions (Zilart)'
    [1377] = 'Rise of the Zilart 1',
    [1378] = 'Rise of the Zilart 2',
    [1379] = 'Rise of the Zilart 3',
    [1380] = 'Rise of the Zilart 4',
    [1381] = 'Rise of the Zilart 5',
    [1382] = 'Rise of the Zilart 6',
    [1383] = 'Rise of the Zilart 7',
    [1384] = 'Rise of the Zilart 8',
    [1385] = 'Rise of the Zilart 9',
    [1386] = 'Rise of the Zilart 10',
    [1387] = 'Rise of the Zilart 11',
    [1388] = 'Rise of the Zilart 12',
    [1389] = 'Rise of the Zilart 13',
    [1390] = 'Rise of the Zilart 14',
    [1391] = 'Rise of the Zilart 15',
    [1392] = 'Rise of the Zilart 16',
    -- 'Missions (Promathia)'
    [1393] = 'Chains of Promathia Chapter 1',
    [1394] = 'Chains of Promathia Chapter 2',
    [1395] = 'Chains of Promathia Chapter 3',
    [1396] = 'Chains of Promathia Chapter 4',
    [1397] = 'Chains of Promathia Chapter 5',
    [1398] = 'Chains of Promathia Chapter 6',
    [1399] = 'Chains of Promathia Chapter 7',
    [1400] = 'Chains of Promathia Chapter 8',
    -- 'Missions (Aht Urhgan)'
    [1410] = 'Treasures of Aht Urhgan 1',
    [1411] = 'Treasures of Aht Urhgan 2',
    [1412] = 'Treasures of Aht Urhgan 3',
    [1413] = 'Treasures of Aht Urhgan 4',
    [1414] = 'Treasures of Aht Urhgan 5',
    [1415] = 'Treasures of Aht Urhgan 6',
    -- 'Missions (Altana)'
    [1402] = 'Wings of the Goddess 1',
    [1403] = 'Wings of the Goddess 2',
    [1404] = 'Wings of the Goddess 3',
    [1405] = 'Wings of the Goddess 4',
    [1406] = 'Wings of the Goddess 5',
    [1407] = 'Wings of the Goddess 6',
    [1408] = 'Wings of the Goddess 7',
    [1409] = 'Wings of the Goddess 8',
    -- 'Missions (Adoulin)'
    [1426] = 'Seekers of Adoulin Chapter 1',
    [1427] = 'Seekers of Adoulin Chapter 2',
    [1428] = 'Seekers of Adoulin Chapter 3',
    [1429] = 'Seekers of Adoulin Chapter 4',
    [1430] = 'Seekers of Adoulin Chapter 5',
    -- 'Combat (General)'
    [12] = 'Vanquish Multiple Enemies I',
    [13] = 'Vanquish Multiple Enemies II',
    [14] = 'Vanquish Multiple Enemies III',
    [15] = 'Level Sync to Vanquish Enemies I',
    [117] = 'Level Sync to Vanq. Enemies II',
    [16] = 'Deal 500+ Damage',
    [17] = 'Deal 1000+ Damage',
    [18] = 'Deal 1500+ Damage',
    [698] = 'Deal 2000+ Damage',
    [19] = 'Deal 10-20 Damage',
    [20] = 'Deal 110-120 Damage',
    [21] = 'Deal 310-320 Damage',
    [22] = 'Deal 510-520 Damage',
    [23] = 'Deal 1110-1120 Damage',
    [29] = 'Total Damage I',
    [30] = 'Total Damage II',
    [696] = 'Total Damage III',
    [31] = 'Total Healing I',
    [32] = 'Total Healing II',
    [699] = 'Total Healing III',
    [33] = 'Total Damage Taken I',
    [34] = 'Total Damage Taken II',
    [697] = 'Total Damage Taken III',
    [45] = 'Weapon Skills I',
    [488] = 'Heal for 500+ HP',
    [700] = 'Heal for 750+ HP',
    -- 'Combat (Spoils) 1'
    [71] = 'Spoils (Fire Crystal)',
    [72] = 'Spoils (Ice Crystal)',
    [73] = 'Spoils (Wind Crystal)',
    [74] = 'Spoils (Earth Crystal)',
    [75] = 'Spoils (Lightning Crystal)',
    [76] = 'Spoils (Water Crystal)',
    [77] = 'Spoils (Light Crystal)',
    [78] = 'Spoils (Dark Crystal)',
    [84] = 'Spoils (Flame Geode)',
    [85] = 'Spoils (Snow Geode)',
    [86] = 'Spoils (Breeze Geode)',
    [87] = 'Spoils (Soil Geode)',
    [88] = 'Spoils (Thunder Geode)',
    [89] = 'Spoils (Aqua Geode)',
    [90] = 'Spoils (Light Geode)',
    [91] = 'Spoils (Shadow Geode)',
    [92] = 'Spoils (Ifritite)',
    [93] = 'Spoils (Shivite)',
    [94] = 'Spoils (Garudite)',
    [95] = 'Spoils (Titanite)',
    [96] = 'Spoils (Ramuite)',
    [97] = 'Spoils (Leviatite)',
    [98] = 'Spoils (Carbite)',
    [99] = 'Spoils (Fenrite)',
    -- 'Combat (Spoils) 2'
    [120] = 'Spoils (Bat Wing)',
    [121] = 'Spoils (Black Tiger Fang)',
    [122] = 'Spoils (Flint Stone)',
    [123] = 'Spoils (Rabbit Hide)',
    [124] = 'Spoils (Honey)',
    [125] = 'Spoils (Sheepskin)',
    [126] = 'Spoils (Lizard Skin)',
    [127] = 'Spoils (Beetle Shell)',
    [128] = 'Spoils (Zeruhn Soot)',
    [129] = 'Spoils (Silver Name Tag)',
    [130] = 'Spoils (Quadav Helm)',
    [132] = 'Spoils (Treant Bulb)',
    [133] = 'Spoils (Wild Onion)',
    [134] = 'Spoils (Sleepshroom)',
    [135] = 'Spoils (Sand Bat Fang)',
    [136] = 'Spoils (Zinc Ore)',
    [137] = 'Spoils (Giant Bird Feather)',
    [138] = 'Spoils (Three-leaf Mandragora Bud)',
    [139] = 'Spoils (Four-leaf Mandragora Bud)',
    [140] = 'Spoils (Cornette)',
    [141] = 'Spoils (Yuhtunga Sulfur)',
    [142] = 'Spoils (Snobby Letter)',
    [143] = 'Spoils (Yagudo Bead Necklace)',
    [144] = 'Spoils (Woozyshroom)',
    [145] = 'Spoils (Beehive Chip)',
    [146] = 'Spoils (Remi Shell)',
    [147] = 'Spoils (Twinstone Earring)',
    -- 'Combat (Original Areas 1)'
    [215] = 'Conflict: West Ronfaure',
    [216] = 'Subjugation: Jaggedy-Eared Jack',
    [217] = 'Conflict: East Ronfaure',
    [218] = 'Subjugation: Swamfisk',
    [219] = 'Conflict: Ghelsba Outpost',
    [220] = 'Subjugation: Thousandarm Deshglesh',
    [221] = 'Conflict: Fort Ghelsba',
    [222] = 'Subjugation: Hundredscar Hajwaj',
    [223] = 'Conflict: Yughott Grotto',
    [224] = 'Subjugation: Ashmaker Gotblut',
    [225] = 'Conflict: King Ranperre\'s Tomb',
    [226] = 'Subjugation: Barbastelle',
    [227] = 'Conflict: Bostaunieux Oubliette',
    [228] = 'Subjugation: Bloodsucker',
    [229] = 'Conflict: Valkurm Dunes',
    [230] = 'Subjugation: Valkurm Emperor',
    [231] = 'Conflict: Konschtat Highlands',
    [232] = 'Subjugation: Bendigeit Vran',
    [233] = 'Conflict: Gusgen Mines',
    [234] = 'Subjugation: Juggler Hecatomb',
    [235] = 'Conflict: La Theine Plateau',
    [236] = 'Subjugation: Bloodtear Baldurf',
    [237] = 'Conflict: Ordelle\'s Caves',
    [238] = 'Subjugation: Morbolger',
    -- 'Combat (Original Areas 2)'
    [239] = 'Conflict: Jugner Forest',
    [240] = 'Subjugation: King Arthro',
    [241] = 'Conflict: Batallia Downs',
    [242] = 'Subjugation: Lumber Jack',
    [243] = 'Conflict: Eldieme Necropolis',
    [244] = 'Subjugation: Cwn Cyrff',
    [245] = 'Conflict: Davoi',
    [246] = 'Subjugation: Hawkeyed Dnatbat',
    [247] = 'Conflict: North Gustaburg',
    [248] = 'Subjugation: Maighdean Uaine',
    [249] = 'Conflict: South Gustaburg',
    [250] = 'Subjugation: Carnero',
    [251] = 'Conflict: Zeruhn Mines',
    [252] = 'Conflict: Palborough Mines',
    [253] = 'Subjugation: Zi\'Ghi Boneeater',
    [254] = 'Conflict: Dangruf Wadi',
    [255] = 'Subjugation: Teporingo',
    [256] = 'Conflict: Pashhow Marshlands',
    [257] = 'Subjugation: Ni\'Zho Bladebender',
    [258] = 'Conflict: Rolanberry Fields',
    [259] = 'Subjugation: Simurgh',
    [260] = 'Conflict: Crawlers\' Nest',
    [261] = 'Subjugation: Demonic Tiphia',
    [262] = 'Conflict: Beadeaux',
    [263] = 'Subjugation: Zo\'Khu Blackcloud',
    -- 'Combat (Original Areas 3)'
    [264] = 'Conflict: West Sarutabaruta',
    [265] = 'Subjugation: Nunyenunc',
    [266] = 'Conflict: East Sarutabaruta',
    [267] = 'Subjugation: Spiny Spipi',
    [268] = 'Conflict: Giddeus',
    [269] = 'Subjugation: Hoo Mjuu the Torrent',
    [270] = 'Conflict: Toraimarai Canal',
    [271] = 'Subjugation: Oni Carcass',
    [272] = 'Conflict: Inner Horutoto Ruins',
    [273] = 'Subjugation: Maltha',
    [274] = 'Conflict: Outer Horutoto Ruins',
    [275] = 'Subjugation: Bomb King',
    [276] = 'Conflict: Buburimu Peninsula',
    [277] = 'Subjugation: Helldiver',
    [278] = 'Conflict: Tahrongi Canyon',
    [279] = 'Subjugation: Serpopard Ishtar',
    [280] = 'Conflict: Maze of Shakhrami',
    [281] = 'Subjugation: Argus',
    [282] = 'Conflict: Meriphataud Mountains',
    [283] = 'Subjugation: Daggerclaw Dracos',
    [284] = 'Conflict: Sauromugue Champaign',
    [285] = 'Subjugation: Roc',
    [286] = 'Conflict: Garlaige Citadel',
    [287] = 'Subjugation: Serket',
    [288] = 'Conflict: Castle Oztroja',
    [289] = 'Subjugation: Lii Jixa the Somnolist',
    -- 'Combat (Original Areas 4)'
    [290] = 'Conflict: Beaucedine Glacier',
    [291] = 'Subjugation: Nue',
    [292] = 'Conflict: Ranguemont Pass',
    [293] = 'Subjugation: Gloom Eye',
    [294] = 'Conflict: Fei\'Yin',
    [295] = 'Subjugation: Goliath',
    [296] = 'Conflict: Xarcabard',
    [297] = 'Subjugation: Biast',
    [298] = 'Conflict: Castle Zvahl Baileys',
    [299] = 'Subjugation: Duke Haborym',
    [300] = 'Conflict: Castle Zvahl Keep',
    [301] = 'Subjugation: Baron Vapula',
    [302] = 'Conflict: Qufim Island',
    [303] = 'Subjugation: Dosetsu Tree',
    [304] = 'Conflict: Lower Delkfutt\'s Tower',
    [305] = 'Subjugation: Epialtes',
    [306] = 'Conflict: Middle Delkfutt\'s Tower',
    [307] = 'Subjugation: Ogygos',
    [308] = 'Conflict: Upper Delkfutt\'s Tower',
    [309] = 'Subjugation: Enkelados',
    [380] = 'Conflict: Behemoth\'s Dominion',
    -- 'Combat (Adoulin 1)'
    [310] = 'Conflict: Rala Waterways I',  -- Spoutddrenched Toads
    [311] = 'Conflict: Rala Waterways II',  -- Stillwater Funguars
    [312] = 'Conflict: Rala Waterways III',  -- Pewter Diremites
    [313] = 'Conflict: Ceizak Battlegrounds I',  -- Blanched Mandragoras
    [314] = 'Conflict: Ceizak Battlegrounds II',  -- Careening Twitherym
    [315] = 'Conflict: Ceizak Battlegrounds III',  -- Resplendent Luckybugs
    [316] = 'Conflict: Yahse Hunting Grounds I',  -- Calfcleaving Chapulis
    [317] = 'Conflict: Yahse Hunting Grounds II',  -- Twitherym Infestations
    [318] = 'Conflict: Yahse Hunting Grounds III',  -- Nettled Wasps
    [319] = 'Conflict: Foret de Hennitiel I',  -- Perfidious Crabs
    [320] = 'Conflict: Foret de Hennitiel II',  -- Scummy Slugs
    [321] = 'Conflict: Foret de Hennitiel III',  -- Vorst Gnats
    [322] = 'Conflict: Morimar Basalt Fields I',  -- Sinewy Matamata
    [323] = 'Conflict: Morimar Basalt Fields II',  -- Tephra Lizards
    [324] = 'Conflict: Morimar Basalt Fields III',  -- Maca Macas
    [325] = 'Conflict: Yorcia Weald I',  -- Snapweeds
    [326] = 'Conflict: Yorcia Weald II',  -- Cheeky Opo-opos
    [327] = 'Conflict: Yorcia Weald III',  -- Bronzecaps
    [328] = 'Conflict: Marjami Ravine I',  -- Vinelash Vultures
    [329] = 'Conflict: Marjami Ravine II',  -- Stryxes
    [330] = 'Conflict: Marjami Ravine III',  -- Lapinions
    -- 'Combat (Adoulin 2)'
    [331] = 'Conflict: Kamihr Drifts I',  -- Snowpelt Rabbits
    [332] = 'Conflict: Kamihr Drifts II',  -- Cicatricose Raaz
    [333] = 'Conflict: Kamihr Drifts III',  -- Shaggy Ovim
    [334] = 'Conflict: Sih Gates I',  -- Bonarias
    [335] = 'Conflict: Sih Gates II',  -- Loathsome Obdellas
    [336] = 'Conflict: Sih Gates III',  -- Ferocious Funguars
    [337] = 'Conflict: Moh Gates I',  -- Conflagrant Erucas
    [338] = 'Conflict: Moh Gates II',  -- Erythemic Efts
    [339] = 'Conflict: Moh Gates III',  -- Writhing Leeches
    [340] = 'Conflict: Cirdas Caverns I',  -- Subterrane Spiders
    [341] = 'Conflict: Cirdas Caverns II',  -- Livid Umbrils
    [342] = 'Conflict: Cirdas Caverns III',  -- Flatus Acuexes
    [343] = 'Conflict: Dho Gates I',  -- Velkk Magi
    [344] = 'Conflict: Dho Gates II',  -- Ripsaw Jagils
    [345] = 'Conflict: Dho Gates III',  -- Unyielding Tarichuks
    [346] = 'Conflict: Woh Gates I',  -- Metalcruncher Worms
    [347] = 'Conflict: Woh Gates II',  -- Drusy Twitherym
    [348] = 'Conflict: Woh Gates III',  -- Wheezing Acuexes
    [494] = 'Conflict: Outer Ra\'Kaznar I',  -- Restless Twitherym
    [495] = 'Conflict: Outer Ra\'Kaznar II',  -- Bristlehair Bats
    [496] = 'Conflict: Outer Ra\'Kaznar III',  -- Astringent Acuexes
    [762] = 'Conflict: Ra\'Kaznar Inner Court I',  -- Bilespouting Acuexes
    [763] = 'Conflict: Ra\'Kaznar Inner Court II',  -- Scowling Vodorigas
    [764] = 'Conflict: Ra\'Kaznar Inner Court III',  -- Unrepentant Byrgen
    -- 'Combat (Zilart 1)'
    [390] = 'Conflict: Sanctuary of Zi\'Tah',
    [392] = 'Conflict: Ro\'Maeve',
    [394] = 'Conflict: Boyahda Tree',
    [396] = 'Conflict: Dragon\'s Aery',
    [398] = 'Conflict: Eastern Altepa Desert',
    [400] = 'Conflict: Western Altepa Desert',
    [402] = 'Conflict: Quicksand Caves',
    [404] = 'Conflict: Gustav Tunnel',
    [406] = 'Conflict: Kuftal Tunnel',
    [408] = 'Conflict: Cape Teriggan',
    [410] = 'Conflict: Valley of Sorrows',
    [412] = 'Conflict: Yuhtunga Jungle',
    -- 'Combat (Zilart 2)'
    [414] = 'Conflict: Sea Serpent Grotto',
    [416] = 'Conflict: Yhoator Jungle',
    [418] = 'Conflict: Temple of Uggalepih',
    [420] = 'Conflict: Den of Rancor',
    [422] = 'Conflict: Ifrit\'s Cauldron',
    [424] = 'Conflict: Ru\'Aun Gardens',
    [426] = 'Conflict: Ve\'Lugannon Palace',
    [428] = 'Conflict: Shrine of Ru\'Avitau',
    [430] = 'Conflict: Labyrinth of Onzozo',
    [432] = 'Conflict: Korroloka Tunnel',
    -- 'Combat (Promathia 1)'
    [434] = 'Conflict: Oldton Movalpolos',
    [436] = 'Conflict: Newton Movalpolos',
    [438] = 'Conflict: Lufaise Meadows',
    [440] = 'Conflict: Misareaux Coast',
    [442] = 'Conflict: Phomiuna Aqueducts',
    [444] = 'Conflict: Riverne - Site #A01',
    [446] = 'Conflict: Riverne - Site #B01',
    [448] = 'Conflict: Sacrarium',
    [450] = 'Conflict: Promyvion - Holla',
    [452] = 'Conflict: Promyvion - Dem',
    [454] = 'Conflict: Promyvion - Mea',
    [456] = 'Conflict: Promyvion - Vahzl',
    -- 'Combat (Promathia 2)'
    [458] = 'Conflict: Al\'Taieu',
    [460] = 'Conflict: Grand Palace of Hu\'Xzoi',
    [462] = 'Conflict: Garden of Ru\'Hmet',
    [464] = 'Conflict: Carpenters\' Landing',
    [468] = 'Conflict: Bibiki Bay',
    [472] = 'Conflict: Attohwa Chasm',
    [474] = 'Conflict: Pso\'Xja',
    [476] = 'Conflict: Uleguerand Range',
    -- 'Combat (Aht Urhgan)'
    [533] = 'Conflict: Bhaflau Thickets',
    [535] = 'Conflict: Mamook',
    [537] = 'Conflict: Wajaom Woodlands',
    [539] = 'Conflict: Aydeewa Subterrane',
    [541] = 'Conflict: Halvung',
    [543] = 'Conflict: Mount Zhayolm',
    [545] = 'Conflict: Caedarva Mire',
    [547] = 'Conflict: Arrapago Reef',
    [549] = 'Conflict: Alza. Undersea Ruins',
    -- 'Combat (Goddess 1)'
    [553] = 'Conflict: East Ronfaure [S]',
    [555] = 'Conflict: Jugner Forest [S]',
    [557] = 'Conflict: Batallia Downs [S]',
    [559] = 'Conflict: La Vaule [S]',
    [561] = 'Conflict: Eldieme Necropolis [S]',
    [563] = 'Conflict: North Gustaberg [S]',
    [565] = 'Conflict: Grauberg [S]',
    [567] = 'Conflict: Vunkerl Inlet [S]',
    [569] = 'Conflict: Pashhow Marshlands [S]',
    [571] = 'Conflict: Rolanberry Fields [S]',
    [573] = 'Conflict: Beadeaux [S]',
    [575] = 'Conflict: Crawlers\' Nest [S]',
    -- 'Combat (Goddess 2)'
    [577] = 'Conflict: West Sarutabaruta [S]',
    [579] = 'Conflict: Fort Karugo-Narugo [S]',
    [581] = 'Conflict: Meriph. Mountains [S]',
    [583] = 'Conflict: Sauro. Champaign [S]',
    [585] = 'Conflict: Castle Oztroja [S]',
    [587] = 'Conflict: Garlaige Citadel [S]',
    [589] = 'Conflict: Beaucedine Glacier [S]',
    [591] = 'Conflict: Xarcabard [S]',
    [593] = 'Conflict: Castle Zvahl Baileys [S]',
    [595] = 'Conflict: Castle Zvahl Keep [S]',
    -- 'Combat (Abyssea)'
    [613] = 'Conflict: Abyssea - La Theine',
    [614] = 'Conflict: Abyssea - Konshtat',
    [615] = 'Conflict: Abyssea - Tahrongi',
    [616] = 'Conflict: Abyssea - Attohwa',
    [617] = 'Conflict: Abyssea - Misareaux',
    [618] = 'Conflict: Abyssea - Vunkerl',
    [619] = 'Conflict: Abyssea - Altepa',
    [620] = 'Conflict: Abyssea - Uleguerand',
    [621] = 'Conflict: Abyssea - Grauberg',
    -- 'Combat (Escha 1)'
    [885] = 'Conflict: Escha - Zi\'Tah I',  -- yztargs
    [886] = 'Conflict: Escha - Zi\'Tah II', -- buggards
    [887] = 'Conflict: Escha - Zi\'Tah III', -- tarichuks
    [888] = 'Conflict: Escha - Zi\'Tah IV', -- s.dragons
    [889] = 'Conflict: Escha - Zi\'Tah V', -- mosquitos
    [901] = 'Conflict: Escha - Zi\'Tah VI', -- puks
    [902] = 'Conflict: Escha - Zi\'Tah VII', -- opo-opos
    [903] = 'Conflict: Escha - Ru\'Aun I',  -- ll'aerns
    [904] = 'Conflict: Escha - Ru\'Aun II',  -- phuabo
    [905] = 'Conflict: Escha - Ru\'Aun III',  -- euvhi
    [906] = 'Conflict: Escha - Ru\'Aun IV',  -- clionidae
    [907] = 'Conflict: Escha - Ru\'Aun V',  -- hpemde
    [908] = 'Conflict: Escha - Ru\'Aun VI',  -- amoebans
    [909] = 'Conflict: Escha - Ru\'Aun VII',  -- xzomit
    [910] = 'Conflict: Escha - Ru\'Aun VIII',  -- murex
    [911] = 'Conflict: Escha - Ru\'Aun IX',  -- ghrahs
    [912] = 'Conflict: Escha - Ru\'Aun X',  -- limules
    -- 'Combat (Escha 2)'
    [943] = 'Conflict: Reisenjima I',  -- Obstreperous Panopts
    [944] = 'Conflict: Reisenjima II',  -- Snaggletoothed Tigers
    [945] = 'Conflict: Reisenjima III',  -- Agitated Chapulis
    [946] = 'Conflict: Reisenjima IV', -- Indomitable Faaz
    [947] = 'Conflict: Reisenjima V',  -- Territorial Mantises
    [948] = 'Conflict: Reisenjima VI', -- Devouring Mosquitos
    [949] = 'Conflict: Reisenjima VII',  -- Lentic Toads
    [950] = 'Conflict: Reisenjima VIII',  -- Quarrelsome Hippogryphs
    [951] = 'Conflict: Reisenjima IX',  -- Rampaging Beetles
    [952] = 'Conflict: Reisenjima X',  -- Glowering Ladybugs
    [953] = 'Conflict: Reisenjima XI',  -- Lucani
    -- 'Fishing: General'
    [1000] = 'Speak to Fisherman\'s Guild Master',
    [1001] = 'Reel in a Catch',
    [1002] = 'Reel in Multiple Small Fish I',
    [1003] = 'Reel in Multiple Big Fish I',
    [1004] = 'Reel in Multiple Rusted Objects',
    [1005] = 'Total Enemies Reeled In',
    [1006] = 'Participate in Fish Ranking',
    [1007] = 'Total Catches (Anywhere)',
    [1008] = 'Total Catches (Saltwater)',
    [1009] = 'Total Catches (Freshwater)',
    [1010] = 'Fish with a Willow Fishing Rod',
    [1011] = 'Fish with a Yew Fishing Rod',
    [1012] = 'Fish with a Bamboo Fishing Rod',
    -- 'Fishing: Tenacity'
    [1039] = 'Reel In 10 Different Catches',
    [1040] = 'Reel In 25 Different Catches',
    [1041] = 'Reel In 50 Different Catches',
    [1042] = 'Reel In 75 Different Catches',
    [1043] = 'Reel In 100 Different Catches',
    [1014] = 'Reel Endurance 1',
    [1015] = 'Reel Endurance 2',
    [1016] = 'Reel Endurance 3',
    [1017] = 'Reel Endurance 4',
    [1018] = 'Reel Endurance 5',
    [1019] = 'Reel Endurance 6',
    [1020] = 'Reel Endurance 7',
    [1021] = 'Reel Endurance 8',
    [1022] = 'Catch Size and Weight',
    [1023] = 'Region: Ronfaure',
    [1024] = 'Region: Gustaberg',
    [1025] = 'Region: Sarutabaruta',
    [1026] = 'Region: Zulkheim',
    [1027] = 'Region: Kolshuhu',
    [1028] = 'Region: Norvallen',
    [1029] = 'Region: Derfland',
    [1030] = 'Region: Aragoneau',
    [1031] = 'Region: Qufim',
    [1032] = 'Region: Fauregandi',
    [1033] = 'Region: Kuzotz',
    [1034] = 'Region: Vollbow',
    [1035] = 'Region: Elshimo Lowlands',
    [1036] = 'Region: Elshimo Uplands',
    [1037] = 'Region: Li\'Telor',
    [1038] = 'Region: Selbina - Mhuara Ferry',
    -- 'Crafting: General'
    -- [57] = 'Total Successful Synthesis Attempts' -- Not even sure if this category exists.
    -- 'Crafting: Escutcheons (Woodworking)'
    [2168] = 'Guild Master\'s Request 1',
    [2169] = 'Guild Master\'s Request 2',
    [2170] = 'Guild Master\'s Request 3',
    [2171] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Clothcraft)'
    [2172] = 'Guild Master\'s Request 1',
    [2173] = 'Guild Master\'s Request 2',
    [2174] = 'Guild Master\'s Request 3',
    [2175] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Alchemy)'
    [2176] = 'Guild Master\'s Request 1',
    [2177] = 'Guild Master\'s Request 2',
    [2178] = 'Guild Master\'s Request 3',
    [2179] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Bonecraft)'
    [2180] = 'Guild Master\'s Request 1',
    [2181] = 'Guild Master\'s Request 2',
    [2182] = 'Guild Master\'s Request 3',
    [2183] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Cooking)'
    [2184] = 'Guild Master\'s Request 1',
    [2185] = 'Guild Master\'s Request 2',
    [2186] = 'Guild Master\'s Request 3',
    [2187] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Goldsmithing)'
    [2188] = 'Guild Master\'s Request 1',
    [2189] = 'Guild Master\'s Request 2',
    [2190] = 'Guild Master\'s Request 3',
    [2191] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Leathercraft)'
    [2192] = 'Guild Master\'s Request 1',
    [2193] = 'Guild Master\'s Request 2',
    [2194] = 'Guild Master\'s Request 3',
    [2195] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Smithing)'
    [2196] = 'Guild Master\'s Request 1',
    [2197] = 'Guild Master\'s Request 2',
    [2198] = 'Guild Master\'s Request 3',
    [2199] = 'Guild Master\'s Request 4',
    -- 'Harvesting (General)'
    [61] = 'Total Successful Harvesting Attempts',
    [118] = 'Total Suc. Harvesting Attempts II',
    -- 'Harvesting (Original Areas)'
    [180] = 'Harvesting: East Ronfaure',
    [181] = 'Harvesting: Ghelsba Outpost',
    [182] = 'Harvesting: Gusgen Mines',
    [183] = 'Harvesting: Jugner Forest',
    [184] = 'Harvesting: Zeruhn Mines',
    [185] = 'Harvesting: Palborough Mines',
    [186] = 'Harvesting: West Sarutabaruta',
    [187] = 'Harvesting: Giddeus',
    [188] = 'Harvesting: Buburimu Penisula',
    [189] = 'Harvesting: Tahrongi Canyon',
    [190] = 'Harvesting: Maze of Shakhrami',
    [389] = 'Harvesting: Yughott Grotto',
    -- 'Harvesting (Adoulin 1)'
    [191] = 'Harvesting: Ceizak Battlegrounds I',
    [192] = 'Harvesting: Ceizak Battlegrounds II',
    [193] = 'Harvesting: Yahse Hunting Grounds I',
    [194] = 'Harvesting: Yahse Hunting Grounds II',
    [195] = 'Harvesting: Foret de Hennetiel I',
    [196] = 'Harvesting: Foret de Hennetiel II',
    [197] = 'Harvesting: Morimar Basalt Fields I',
    [198] = 'Harvesting: Morimar Basalt Fields II',
    [199] = 'Harvesting: Yorcia Weald I',
    [200] = 'Harvesting: Yorcia Weald II',
    [201] = 'Harvesting: Marjami Ravine I',
    [202] = 'Harvesting: Marjami Ravine II',
    [203] = 'Harvesting: Kamihr Drifts I',
    [204] = 'Harvesting: Kamihr Drifts II',
    [205] = 'Harvesting: Sih Gates I',
    [206] = 'Harvesting: Sih Gates II',
    [207] = 'Harvesting: Moh Gates I',
    [208] = 'Harvesting: Moh Gates II',
    [209] = 'Harvesting: Cirdas Caverns I',
    [210] = 'Harvesting: Cirdas Caverns II',
    [211] = 'Harvesting: Dho Gates I',
    [212] = 'Harvesting: Dho Gates II',
    [213] = 'Harvesting: Woh Gates I',
    [214] = 'Harvesting: Woh Gates II',
    [492] = 'Harvesting: Outer Ra\'Kaznar I',
    [493] = 'Harvesting: Outer Ra\'Kaznar II',
    -- 'Harvesting (Zilart)'
    [478] = 'Harvesting: Yuhtunga Jungle',
    [479] = 'Harvesting: Yhoator Jungle',
    [480] = 'Harvesting: Ifrit\'s Cauldron',
    [485] = 'Harvesting: Korroloka Tunnel',
    -- 'Harvesting (Promathia)'
    [481] = 'Harvesting: Oldton Movalpolos',
    [482] = 'Harvesting: Newton Movalpolos',
    [483] = 'Harvesting: Lufaise Meadows',
    [484] = 'Harvesting: Misareaux Coast',
    [486] = 'Harvesting: Carpenters\' Landing',
    [487] = 'Harvesting: Attohwa Chasm',
    -- 'Harvesting (Aht Urhgan)'
    [599] = 'Harvesting: Bhaflau Thickets',
    [600] = 'Harvesting: Mamook',
    [601] = 'Harvesting: Wajaom Woodlands',
    [602] = 'Harvesting: Halvung',
    [603] = 'Harvesting: Mount Zhayolm',
    [604] = 'Harvesting: Caedarva Mire',
    -- 'Harvesting (Goddess)'
    [606] = 'Harvesting: East Ronfaure [S]',
    [607] = 'Harvesting: Jugner Forest [S]',
    [608] = 'Harvesting: North Gustaberg [S]',
    [609] = 'Harvesting: Grauberg [S]',
    [610] = 'Harvesting: West Sarutabaruta [S]',
    [611] = 'Harvesting: Fort Karugo-Narugo [S]',
    -- 'Harvesting (Abyssea)'
    [623] = 'Harvesting: Abyssea - La Thiene',
    [624] = 'Harvesting: Abyssea - Tahronghi',
    [625] = 'Harvesting: Abyssea - Attohwa',
    [626] = 'Harvesting: Abyssea - Misareaux',
    [627] = 'Harvesting: Abyssea - Grauberg',
    -- 'Content (Ambuscade)'
    [3758] = 'Ambuscade Primer Vol. 1 (Daily)',
    [3759] = 'Ambuscade Primer Vol. 2 (Daily)',
    [3995] = 'Intense Ambuscade (M)',
    [3760] = 'Ambuscade (W)',
    [3998] = 'Ambuscade Primer Vol. 1',
    [3999] = 'Ambuscade Primer Vol. 2',
    -- 'Lair Reives'
    [349] = 'Lair Reives: Ceizak Battlegrounds',
    [350] = 'Lair Reives: Yahse Hunting Grounds',
    [351] = 'Lair Reives: Foret de Hennetiel',
    [352] = 'Lair Reives: Morimar Basalt Fields',
    [353] = 'Lair Reives: Yorcia Weald',
    [354] = 'Lair Reives: Marjami Ravine',
    [355] = 'Lair Reives: Kamihr Drifts',
    [358] = 'Lair Reives: Cirdas Caverns',
    [498] = 'Lair Reives: Outer Ra\'Kaznar',
    [765] = 'Lair Reives: Ra\'Kaznar Inner Court',
    -- 'Colonization Reives'
    [361] = 'Colonization Reives: Ceizak',
    [362] = 'Colonization Reives: Yahse',
    [363] = 'Colonization Reives: Hennetiel',
    [364] = 'Colonization Reives: Morimar',
    [365] = 'Colonization Reives: Yorcia Weald',
    [366] = 'Colonization Reives: Marjami Ravine',
    [367] = 'Colonization Reives: Kamihr Drifts',
    [368] = 'Colonization Reives: Sih Gates',
    [369] = 'Colonization Reives: Moh Gates',
    [370] = 'Colonization Reives: Cirdas Caverns',
    [371] = 'Colonization Reives: Dho Gates',
    [372] = 'Colonization Reives: Woh Gates',
    [498] = 'Colonization Reives: Outer Ra\'Kaznar',
    [766] = 'Colonization Reives: Ra\'Kaznar I.C.',
    -- 'Wildskeeper Reives'
    [373] = 'Subjugation: Colkhab',
    [374] = 'Subjugation: Tchakka',
    [375] = 'Subjugation: Achuka',
    [376] = 'Subjugation: Yumcax',
    [377] = 'Subjugation: Hurkan',
    [378] = 'Subjugation: Kumhau',
    -- 'Content (Other)'
    [57] = 'Total Successful Synthesis Attempts',
    [63] = 'Total Suc. Chocobo Digs',
    [65] = 'Mons.: Total Monsters Vanquished',
    [490] = 'Unlock Treasure Chests and Coffers',
    [726] = 'Reaching the Crest',
    [727] = 'Subjugation: Kirin',
    [728] = 'Subjugation: Genbu',
    [729] = 'Subjugation: Suzaku',
    [730] = 'Subjugation: Seiryu',
    [731] = 'Subjugation: Byakko',
    [768] = 'Subjugation: Jailer of Justice',
    [769] = 'Subjugation: Jailer of Hope',
    [770] = 'Subjugation: Jailer of Prudence',
    [771] = 'Subjugation: Jailer of Love',
    [812] = 'Subjugation: Battleclad Chariot',
    [813] = 'Subjugation: Armored Chariot',
    [814] = 'Subjugation: Long-Bowed Chariot',
    [815] = 'Subjugation: Long-Armed Chariot',
    -- 'Content (Dynamis 1)'
    [732] = 'Subjugation: Overlord\'s Tombstone',
    [733] = 'Subjugation: Bladeburner Rokgevok',
    [734] = 'Subjugation: Steelshank Kratzvatz',
    [735] = 'Subjugation: Bloodfist Voshgrosh',
    [736] = 'Subjugation: Spellspear Djokvukk',
    [737] = 'Subjugation: Gu\'Dha Effigy',
    [738] = 'Subjugation: Zo\'Pha Forgesoul',
    [739] = 'Subjugation: Ra\'Gho Darkfount',
    [740] = 'Subjugation: Va\'Zhe Pummelsong',
    [741] = 'Subjugation: Bu\'Bho Truesteel',
    [742] = 'Subjugation: Tzee Xicu Idol',
    [743] = 'Subjugation: Xuu Bhoqa the Enigma',
    [744] = 'Subjugation: Fuu Tzapo the Blessed',
    [745] = 'Subjugation: Naa Yixo the Stillrage',
    [746] = 'Subjugation: Tee Zaksa the Ceaseless',
    [747] = 'Subjugation: Goblin Golem',
    [748] = 'Subjugation: Quicktrix Hexhands',
    [749] = 'Subjugation: Feralox Honeylips',
    [750] = 'Subjugation: Scourquix Scaleskin',
    [751] = 'Subjugation: Wilywox Tenderpalm',
    -- 'Content (Dynamis 2)'
    [752] = 'Subjugation: Angra Mainyu',
    [753] = 'Subjugation: Taquede',
    [754] = 'Subjugation: Pignonpausard',
    [755] = 'Subjugation: Hitaume',
    [756] = 'Subjugation: Cavanneche',
    [757] = 'Subjugation: Dynamis Lord',
    [758] = 'Subjugation: Duke Haures',
    [759] = 'Subjugation: Marquis Caim',
    [760] = 'Subjugation: Baron Avnas',
    [761] = 'Subjugation: Count Haagenti',
    -- 'Content (Limbus)'
    [772] = 'Spoils (Ivory Chip)',
    [773] = 'Spoils (Scarlet Chip)',
    [774] = 'Spoils (Emerald Chip)',
    [775] = 'Spoils (Orchid Chip)',
    [776] = 'Spoils (Cerulean Chip)',
    [777] = 'Spoils (Silver Chip)',
    [778] = 'Spoils (Smoky Chip)',
    [779] = 'Spoils (Magenta Chip)',
    [780] = 'Spoils (Charcoal Chip)',
    [781] = 'Spoils (Smalt Chip)',
    [782] = 'Subjugation: Proto-Ultima',
    [783] = 'Subjugation: Proto-Omega',
    -- 'Content (ZNM)'
    [785] = 'Subjugation: Vulpangue',
    [786] = 'Subjugation: Chamrosh',
    [787] = 'Subjugation: Cheese Hoarder Gigiroon',
    [788] = 'Subjugation: Brass Borer',
    [789] = 'Subjugation: Claret',
    [790] = 'Subjugation: Ob',
    [791] = 'Subjugation: Velionis',
    [792] = 'Subjugation: Lil\' Apkallu',
    [793] = 'Subjugation: Chigre',
    [794] = 'Subjugation: Iriz Ima',
    [795] = 'Subjugation: Lividroot Amooshah',
    [796] = 'Subjugation: Iriri Samariri',
    [797] = 'Subjugation: Anantaboga',
    [798] = 'Subjugation: Reacton',
    [799] = 'Subjugation: Dextrose',
    [800] = 'Subjugation: Wulgaru',
    [801] = 'Subjugation: Zareehkl the Jubilant',
    [802] = 'Subjugation: Verdelet',
    [803] = 'Subjugation: Armed Gears',
    [804] = 'Subjugation: Gotoh Zha the Redolent',
    [805] = 'Subjugation: Dea',
    [806] = 'Subjugation: Nosferatu',
    [807] = 'Subjugation: Khromasoul Bhurborlor',
    [808] = 'Subjugation: Achamoth',
    [809] = 'Subjugation: Mahjlaef the Paintorn',
    [810] = 'Subjugation: Experimental Lamia',
    [811] = 'Subjugation: Nuhn',
    -- 'Content (Vagary)'
    [879] = 'Subjugation: Putraxia',
    [880] = 'Subjugation: Rancibus',
    [881] = 'Subjugation: Palloritus',
    [882] = 'Subjugation: Perfidien',
    [883] = 'Subjugation: Plouton',
    [3400] = 'Subj.: Putraxia 1 (W)',
    [3401] = 'Subj.: Putraxia 2 (W)',
    [3402] = 'Subj.: Rancibus 1 (W)',
    [3403] = 'Subj.: Rancibus 2 (W)',
    [3404] = 'Subj.: Palloritus 1 (W)',
    [3405] = 'Subj.: Palloritus 2 (W)',
    [3406] = 'Subj.: Perfidien 1 (W)',
    [3407] = 'Subj.: Perfidien 2 (W)',
    [3408] = 'Subjugation: Plouton 1 (W)',
    [3409] = 'Subjugation: Plouton 2 (W)',
    -- 'Content (Omen)'
    [970] = 'Subjugation: Fu',
    [971] = 'Subjugation: Kyou',
    [972] = 'Subjugation: Kei',
    [973] = 'Subjugation: Gin',
    [974] = 'Subjugation: Kin',
    -- 'A.M.A.N. Trove'
    [3768] = 'A.M.A.N. Trove (M)',
    [3769] = 'Examine a Home Point (M)',
    [3770] = 'Auction an Item (M)',
    [3771] = 'Unity Chat Greetings (M)',
    [3772] = 'Conquest Participation (M)',
    [3773] = 'Besieged Participation (M)',
    [3774] = 'Campaign Participation (M)',
    [3775] = 'Reive Participation (M)',
    [3776] = 'Ambuscade Participation (M)',
    [3777] = 'Omen Participation (M)',
    [3778] = 'Dynamis - Divergence Participation (M)',
    -- 'Content (Odyssey)'
    [977] = 'Sheol A',
    [978] = 'Sheol B',
    [979] = 'Sheol C',
    -- 'Job Levels 1'
    [1200] = 'Level 30 Warrior',
    [1201] = 'Level 50 Warrior',
    [1202] = 'Level 75 Warrior',
    [1203] = 'Level 99 Warrior',
    [1204] = 'Level 30 Monk',
    [1205] = 'Level 50 Monk',
    [1206] = 'Level 75 Monk',
    [1207] = 'Level 99 Monk',
    [1208] = 'Level 30 White Mage',
    [1209] = 'Level 50 White Mage',
    [1210] = 'Level 75 White Mage',
    [1211] = 'Level 99 White Mage',
    [1212] = 'Level 30 Black Mage',
    [1213] = 'Level 50 Black Mage',
    [1214] = 'Level 75 Black Mage',
    [1215] = 'Level 99 Black Mage',
    [1216] = 'Level 30 Red Mage',
    [1217] = 'Level 50 Red Mage',
    [1218] = 'Level 75 Red Mage',
    [1219] = 'Level 99 Red Mage',
    [1220] = 'Level 30 Thief',
    [1221] = 'Level 50 Thief',
    [1222] = 'Level 75 Theif',
    [1223] = 'Level 99 Thief',
    -- 'Job Levels 2'
    [1224] = 'Level 30 Paladin',
    [1225] = 'Level 50 Paladin',
    [1226] = 'Level 75 Paladin',
    [1227] = 'Level 99 Paladin',
    [1228] = 'Level 30 Dark Knight',
    [1229] = 'Level 50 Dark Knight',
    [1230] = 'Level 75 Dark Knight',
    [1231] = 'Level 99 Dark Knight',
    [1232] = 'Level 30 Beastmaster',
    [1233] = 'Level 50 Beastmaster',
    [1234] = 'Level 75 Beastmaster',
    [1235] = 'Level 99 Beastmaster',
    [1236] = 'Level 30 Bard',
    [1237] = 'Level 50 Bard',
    [1238] = 'Level 75 Bard',
    [1239] = 'Level 99 Bard',
    [1240] = 'Level 30 Ranger',
    [1241] = 'Level 50 Ranger',
    [1242] = 'Level 75 Ranger',
    [1243] = 'Level 99 Ranger',
    [1244] = 'Level 30 Samurai',
    [1245] = 'Level 50 Samurai',
    [1246] = 'Level 75 Samurai',
    [1247] = 'Level 99 Samurai',
    -- 'Job Levels 3'
    [1248] = 'Level 30 Ninja',
    [1249] = 'Level 50 Ninja',
    [1250] = 'Level 75 Ninja',
    [1251] = 'Level 99 Ninja',
    [1252] = 'Level 30 Dragoon',
    [1253] = 'Level 50 Dragoon',
    [1254] = 'Level 75 Dragoon',
    [1255] = 'Level 99 Dragoon',
    [1256] = 'Level 30 Summoner',
    [1257] = 'Level 50 Summoner',
    [1258] = 'Level 75 Summoner',
    [1259] = 'Level 99 Summoner',
    [1260] = 'Level 30 Blue Mage',
    [1261] = 'Level 50 Blue Mage',
    [1262] = 'Level 75 Blue Mage',
    [1263] = 'Level 99 Blue Mage',
    [1264] = 'Level 30 Corsair',
    [1265] = 'Level 50 Corsair',
    [1266] = 'Level 75 Corsair',
    [1267] = 'Level 99 Corsair',
    [1268] = 'Level 30 Puppetmaster',
    [1269] = 'Level 50 Puppetmaster',
    [1270] = 'Level 75 Puppetmaster',
    [1271] = 'Level 99 Puppetmaster',
    -- 'Job Levels 4'
    [1272] = 'Level 30 Dancer',
    [1273] = 'Level 50 Dancer',
    [1274] = 'Level 75 Dancer',
    [1275] = 'Level 99 Dancer',
    [1276] = 'Level 30 Scholar',
    [1277] = 'Level 50 Scholar',
    [1278] = 'Level 75 Scholar',
    [1279] = 'Level 99 Scholar',
    [1280] = 'Level 30 Geomancer',
    [1281] = 'Level 50 Geomancer',
    [1282] = 'Level 75 Geomancer',
    [1283] = 'Level 99 Geomancer',
    [1284] = 'Level 30 Rune Fencer',
    [1285] = 'Level 50 Rune Fencer',
    [1286] = 'Level 75 Rune Fencer',
    [1287] = 'Level 99 Rune Fencer',
    -- 'Fame'
    [1289] = 'Fame: San d\'Oria',
    [1290] = 'Fame: Bastok',
    [1291] = 'Fame: Windurst',
    [1292] = 'Fame: Norg',
    [1293] = 'Fame: Abyssea - La Thiene',
    [1294] = 'Fame: Abyssea - Konschtat',
    [1295] = 'Fame: Abyssea - Tahrongi',
    [1296] = 'Fame: Abyssea - Attohwa',
    [1297] = 'Fame: Abyssea - Misareaux',
    [1298] = 'Fame: Abyssea - Vunkerl',
    [1299] = 'Fame: Abyssea - Altepa',
    [1300] = 'Fame: Abyssea - Uleguerand',
    [1301] = 'Fame: Abyssea - Grauberg',
    [1302] = 'Fame: Adoulin',
-- Unity
    -- Unity (Shared A)
    [3000] = 'Unity Communique A (UC)',
    [3001] = 'Home Point Comrade A (UC)',
    [3002] = 'Vanquish Multiple Enemies  A (UC)',
    [3003] = 'Vanquish Aquans A (UC)',
    [3004] = 'Van. Amorphs with Ph. Damage A (UC)',
    [3005] = 'Vanquish Beasts with Magic A (UC)',
    [3006] = 'Total Suc. Wood. Syntheses A (UC)',
    [3007] = 'Total Suc. Leath. Syntheses A (UC)',
    [3008] = 'Total Suc. Mining Attempts A (UC)',
    [3055] = 'Van. Enemies w. Unity Leader A (UC)',
    -- Unity (Shared B)
    [3009] = 'Unity Communique B (UC)',
    [3010] = 'Chocobo Digging B (UC)',
    [3011] = 'Vanquish Multiple Enemies B (UC)',
    [3012] = 'Vanquish Arcana B (UC)',
    [3013] = 'Van. Undead with Ph. Damage B (UC)',
    [3014] = 'Vanquish Plantoids with Magic B (UC)',
    [3015] = 'Total Suc. Black. Syntheses B (UC)',
    [3016] = 'Reel in Multiple Small Fish B (UC)',
    [3017] = 'Total Suc. Logging Attempts B (UC)',
    [3056] = 'Van. Enemies w. Unity Leader B (UC)',
    -- Unity (Shared C)
    [3018] = 'Unity Communique C (UC)',
    [3019] = 'Home Point Comrade C (UC)',
    [3020] = 'Vanquish Multiple Enemies C (UC)',
    [3021] = 'Vanquish Vermin C (UC)',
    [3022] = 'Van. Birds with Ph. Damage C (UC)',
    [3023] = 'Vanquish Lizards with Magic C (UC)',
    [3024] = 'Total Suc. Gold. Syntheses C (UC)',
    [3025] = 'Reel in Multiple Large Fish C (UC)',
    [3026] = 'Total Suc. Harvesting Attempts C (UC)',
    [3057] = 'Van. Enemies w. Unity Leader C (UC)',
    -- Unity (Shared D)
    [3027] = 'Unity Communique D (UC)',
    [3028] = 'Mons.: Tot. Monsters Vanquished D (UC)',
    [3029] = 'Vanquish Multiple Enemies D (UC)',
    [3030] = 'Vanquish Beasts D (UC)',
    [3031] = 'Van. Aquans with Ph. Damage D (UC)',
    [3032] = 'Vanquish Amorphs with Magic D (UC)',
    [3033] = 'Total Suc. Cloth. Syntheses D (UC)',
    [3034] = 'Total Suc. Bone. Syntheses D (UC)',
    [3035] = 'Total Suc. Mining Attempts D (UC)',
    [3058] = 'Van. Enemies w. Unity Leader D (UC)',
    -- Unity (Shared E)
    [3036] = 'Unity Communique E (UC)',
    [3037] = 'Home Point Comrade E (UC)',
    [3038] = 'Vanquish Multiple Enemies E (UC)',
    [3039] = 'Vanquish Plantiods E (UC)',
    [3040] = 'Van. Arcana with Ph. Damage E (UC)',
    [3041] = 'Vanquish Undead with Magic E (UC)',
    [3042] = 'Total Suc. Cook. Syntheses E (UC)',
    [3043] = 'Total Saltwater Catches E (UC)',
    [3044] = 'Total Suc. Logging Attempts E (UC)',
    [3059] = 'Van. Enemies w. Unity Leader E (UC)',
    -- Unity (Shared F)
    [3045] = 'Unity Communique F (UC)',
    [3046] = 'Level sync to vanquish enemies F (UC)',
    [3047] = 'Vanquish Multiple Enemies F (UC)',
    [3048] = 'Vanquish Lizards F (UC)',
    [3049] = 'Van. Vermin with Ph. Damage F (UC)',
    [3050] = 'Vanquish Birds with Magic F (UC)',
    [3051] = 'Total Suc. Alchemy Syntheses F (UC)',
    [3052] = 'Total Freshwater Catches F (UC)',
    [3053] = 'Total Suc. Harvesting Attempts F (UC)',
    [3060] = 'Van. Enemies w. Unity Leader F (UC)',
-- Unity (Aldo)
    -- Week 0
    [3588] = 'Dagger Weapon Skills (UC)',
    [3589] = 'Conflict: Sanctuary of Zi\'Tah (UC)',
    [3590] = 'Vanquish Hounds (UC)',
    [3591] = 'Subjugation: Bastet (UC)',
    [3592] = 'Heal Unity Allies (UC)',
    -- Week 1
    [3593] = 'Spoils (Doll Shard) (UC)',
    [3594] = 'Conflict: Morimar Basalt Fields (UC)',
    [3595] = 'Vanquish Dolls (UC)',
    [3596] = 'Subjugation: Nocuous Weapon (UC)',
    [3597] = 'Cure Status Ailments (UC)',
    -- Week 2
    [3598] = 'Marksmanship Weapon Skills (UC)',
    [3599] = 'Conflict: Boyahda Tree (UC)',
    [3600] = 'Vanquish Slimes (UC)',
    [3601] = 'Subjugation: Aquarius (UC)',
    [3602] = 'Heal Unity Allies (UC)',
    -- Week 3
    [3603] = 'Spoils (Bird Egg) (UC)',
    [3604] = 'Conflict: Western Altepa Desert (UC)',
    [3605] = 'Vanquish Crow-Type Birds (UC)',
    [3606] = 'Subjugation: Cactuar Cantautor (UC)',
    [3607] = 'Magic Bursts (UC)',
-- Unity (Apururu)
    -- Week 0
    [3548] = 'Club Weapon Skills (UC)',
    [3549] = 'Conflict: West Sarutabaruta (UC)',
    [3550] = 'Vanquish Bees (UC)',
    [3551] = 'Subjugation: Tom Tit Tat (UC)',
    [3552] = 'Heal Unity Allies (UC)',
    -- Week 1
    [3553] = 'Spoils (Silk Thread) (UC)',
    [3554] = 'Conflict: Buburimu Peninsula (UC)',
    [3555] = 'Vanquish Crawlers (UC)',
    [3556] = 'Subjugation: Buburimboo (UC)',
    [3557] = 'Cure Status Ailments (UC)',
    -- Week 2
    [3558] = 'Staff Weapon Skills (UC)',
    [3559] = 'Conflict: Castle Oztroja (UC)',
    [3560] = 'Vanquish Ghosts (UC)',
    [3561] = 'Subj.: Mee Deggi the Punisher (UC)',
    [3562] = 'Heal Unity Allies (UC)',
    -- Week 3
    [3563] = 'Spoils (Saruta Cotton) (UC)',
    [3564] = 'Conflict: Foret de Hennetiel (UC)',
    [3565] = 'Vanquish Mandragoras (UC)',
    [3566] = 'Subj.: Juu Duzu the Whirlwind (UC)',
    [3567] = 'Magic Bursts (UC)',
-- Unity (Ayame)
    -- Week 0
    [3508] = 'Great Katana Weapon Skills (UC)',
    [3509] = 'North Gustaberg (UC)',
    [3510] = 'Vanquish Worms (UC)',
    [3511] = 'Subjugation: Stinging Sophie (UC)',
    [3512] = 'Heal Unity Allies (UC)',
    -- Week 1
    [3513] = 'Spoils (Cockatrice Meat) (UC)',
    [3514] = 'Conflict: Yahse Hunting Grounds (UC)',
    [3515] = 'Vanquish Cockatrices (UC)',
    [3516] = 'Subjugation: Tococo (UC)',
    [3517] = 'Cure Status Ailments (UC)',
    -- Week 2
    [3518] = 'Archery Weapon Skills (UC)',
    [3519] = 'Conflict: Crawlers\' Nest (UC)',
    [3520] = 'Vanquish Lizards (UC)',
    [3521] = 'Subjugation: Aqrabuamelu (UC)',
    [3522] = 'Heal Unity Allies (UC)',
    -- Week 3
    [3523] = 'Spoils (Land Crab Meat) (UC)',
    [3524] = 'Conflict: Beadeaux (UC)',
    [3525] = 'Vanquish Crabs (UC)',
    [3526] = 'Subjugation: Ge\'Dha Evileye (UC)',
    [3527] = 'Magic Bursts (UC)',
-- Unity (Flaviria)
    -- Week 0
    [3648] = 'Polearm Weapon Skills (UC)',
    [3649] = 'Conflict: Cirdas Caverns (UC)',
    [3650] = 'Vanquish Pugils (UC)',
    [3651] = 'Subjugation: Hovering Hotpot (UC)',
    [3652] = 'Heal Unity Allies (UC)',
    -- Week 1
    [3653] = 'Spoils (Beetle Shell) (UC)',
    [3654] = 'Conflict: East Ronfaure (UC)',
    [3655] = 'Vanquish Beetles (UC)',
    [3656] = 'Subjugation: Bigmouth Billy (UC)',
    [3657] = 'Cure Status Ailments (UC)',
    -- Week 2
    [3658] = 'Sword Weapon Skills (UC)',
    [3659] = 'Conflict: Xarcabard (UC)',
    [3660] = 'Vanquish Goobbues (UC)',
    [3661] = 'Subjugation: Barbaric Weapon (UC)',
    [3662] = 'Heal Unity Allies (UC)',
    -- Week 3
    [3663] = 'Spoils (Bone Chip) (UC)',
    [3664] = 'Conflict: Woh Gates (UC)',
    [3665] = 'Vanquish Skeletons (UC)',
    [3666] = 'Subjugation: Hyakume (UC)',
    [3667] = 'Magic Bursts (UC)',
-- Unity (Invincible Shield)
    -- Week 0
    [3528] = 'Axe Weapon Skills (UC)',
    [3529] = 'Conflict: South Gustaberg (UC)',
    [3530] = 'Vanquish Sea Monks (UC)',
    [3531] = 'Subjugation: Leaping Lizzy (UC)',
    [3532] = 'Heal Unity Allies (UC)',
    -- Week 1
    [3533] = 'Spoils (Sleepshroom) (UC)',
    [3534] = 'Conflict: Pashhow Marshlands (UC)',
    [3535] = 'Vanquish Funguars (UC)',
    [3536] = 'Subjugation: Bloodpool Vorax (UC)',
    [3537] = 'Cure Status Ailments (UC)',
    -- Week 2
    [3538] = 'Great Axe Weapon Skills (UC)',
    [3539] = 'Conflict: Ceizak Battlegrounds (UC)',
    [3540] = 'Vanquish Flies (UC)',
    [3541] = 'Subjugation: Be\'Hya Hundredwall (UC)',
    [3542] = 'Heal Unity Allies (UC)',
    -- Week 3
    [3543] = 'Spoils (Raptor Skin) (UC)',
    [3544] = 'Conflict: Beaucedine Glacier (UC)',
    [3545] = 'Vanquish Raptors (UC)',
    [3546] = 'Subjugation: Gargantua (UC)',
    [3547] = 'Magic Bursts (UC)',
-- Unity (Jakoh Wahcondalo)
    -- Week 0
    [3608] = 'Dagger Weapon Skills (UC)',
    [3609] = 'Conflict: Yuhtunga Jungle (UC)',
    [3610] = 'Vanquish Sheep (UC)',
    [3611] = 'Subj.: Mischievous Micholas (UC)',
    [3612] = 'Heal Unity Allies (UC)',
    -- Week 1
    [3613] = 'Spoils (Scorpion Claw) (UC)',
    [3614] = 'Conflict: East Sarutabaruta (UC)',
    [3615] = 'Vanquish Scorpions (UC)',
    [3616] = 'Subjugation: Sharp-Eared Ropipi (UC)',
    [3617] = 'Cure Status Ailments (UC)',
    -- Week 2
    [3618] = 'Archery Weapon Skills (UC)',
    [3619] = 'Conflict: Marjami Ravine (UC)',
    [3620] = 'Vanquish Opo-opos (UC)',
    [3621] = 'Subjugation: Ah Puch (UC)',
    [3622] = 'Heal Unity Allies (UC)',
    -- Week 3
    [3623] = 'Spoils (Black Tiger Fang) (UC)',
    [3624] = 'Conflict: Sea Serpent Grotto (UC)',
    [3625] = 'Vanquish Tigers (UC)',
    [3626] = 'Subjugation: Fyuu the Seabellow (UC)',
    [3627] = 'Magic Bursts (UC)',
-- Unity (Maat)
    -- Week 0
    [3568] = 'Hand-to-Hand Weapon Skills (UC)',
    [3569] = 'Conflict: Yorcia Weald (UC)',
    [3570] = 'Vanquish Leeches (UC)',
    [3571] = 'Subjugation: Canal Moocher (UC)',
    [3572] = 'Heal Unity Allies (UC)',
    -- Week 1
    [3573] = 'Spoils (Spider Web) (UC)',
    [3574] = 'Conflict: Rolanberry Fields (UC)',
    [3575] = 'Vanquish Spiders (UC)',
    [3576] = 'Subjugation: Eldritch Edge (UC)',
    [3577] = 'Cure Status Ailments (UC)',
    -- Week 2
    [3578] = 'Great Sword Weapon Skills (UC)',
    [3579] = 'Conflict: Meriphataud Mountains (UC)',
    [3580] = 'Vanquish Wyverns (UC)',
    [3581] = 'Subjugation: Patripatan (UC)',
    [3582] = 'Heal Unity Allies (UC)',
    -- Week 3
    [3583] = 'Spoils (Hecteyes Eye) (UC)',
    [3584] = 'Conflict: Sauromugue Champaign (UC)',
    [3585] = 'Vanquish Hecteyes (UC)',
    [3586] = 'Subjugation: Bashe (UC)',
    [3587] = 'Magic Bursts (UC)',
-- Unity (Naja Salaheem)
    -- Week 0
    [3628] = 'Club Weapon Skills (UC)',
    [3629] = 'Conflict: Bhaflau Thickets (UC)',
    [3630] = 'Vanquish Evil Weapons (UC)',
    [3631] = 'Subjugation: Emergent Elm (UC)',
    [3632] = 'Heal Unity Allies (UC)',
    -- Week 1
    [3633] = 'Spoils (Puk Wing) (UC)',
    [3634] = 'Conflict: West Ronfaure (UC)',
    [3635] = 'Vanquish Puks (UC)',
    [3636] = 'Subjugation: Fungus Beetle (UC)',
    [3637] = 'Cure Status Ailments (UC)',
    -- Week 2
    [3638] = 'Staff Weapon Skills (UC)',
    [3639] = 'Conflict: Wajaom Woodlands (UC)',
    [3640] = 'Vanquish Elementals (UC)',
    [3641] = 'Subjugation: Jaded Jody (UC)',
    [3642] = 'Heal Unity Allies (UC)',
    -- Week 3
    [3643] = 'Spoils (Dhalmel Meat) (UC)',
    [3644] = 'Conflict: Kamihr Drifts (UC)',
    [3645] = 'Vanquish Dhalmel (UC)',
    [3646] = 'Subjugation: Trembler Tabitha (UC)',
    [3647] = 'Magic Bursts (UC)',
-- Unity (Pieuje)
    -- Week 0
    [3488] = 'Club Weapon Skills (UC)',
    [3489] = 'Conflict: Rala Waterways (UC)',
    [3490] = 'Vanquish Rabbits (UC)',
    [3491] = 'Subjugation: Rambukk (UC)',
    [3492] = 'Heal Unity Allies (UC)',
    -- Week 1
    [3493] = 'Spoils (Bat Fang) (UC)',
    [3494] = 'Conflict: La Theine Plateau (UC)',
    [3495] = 'Vanquish Bats (UC)',
    [3496] = 'Subjugation: Tumbling Truffle (UC)',
    [3497] = 'Cure Status Ailments (UC)',
    -- Week 2
    [3498] = 'Staff Weapon Skills (UC)',
    [3499] = 'Conflict: Eldieme Necropolis (UC)',
    [3500] = 'Vanquish Treants (UC)',
    [3501] = 'Subjugation: Duke Decapod (UC)',
    [3502] = 'Heal Unity Allies (UC)',
    -- Week 3
    [3503] = 'Spoils (Bomb Ash) (UC)',
    [3504] = 'Conflict: Davoi (UC)',
    [3505] = 'Vanquish Bombs (UC)',
    [3506] = 'Subj.: Poisonhand Gnadgad (UC)',
    [3507] = 'Magic Bursts (UC)',
-- Unity (Sylvie)
    -- Week 0
    [3688] = 'Club Weapon Skills (UC)',
    [3689] = 'Conflict: Sih Gates (UC)',
    [3690] = 'Vanquish Acuex (UC)',
    [3691] = 'Subjugation: Intulo (UC)',
    [3692] = 'Heal Unity Allies (UC)',
    -- Week 1
    [3693] = 'Spoils (Demon Horn) (UC)',
    [3694] = 'Conf.: Konschtat Highlands (UC)',
    [3695] = 'Vanquish Demons (UC)',
    [3696] = 'Subj.: Marquis Naberius (UC)',
    [3697] = 'Cure Status Ailments (UC)',
    -- Week 2
    [3698] = 'Staff Weapon Skills (UC)',
    [3699] = 'Conflict: Dho Gates (UC)',
    [3700] = 'Vanquish Velkk (UC)',
    [3701] = 'Subjugation: Dune Widow (UC)',
    [3702] = 'Heal Unity Allies (UC)',
    -- Week 3
    [3703] = 'Spoils (Twitherym Wing) (UC)',
    [3704] = 'Conflict: Qufim Island (UC)',
    [3705] = 'Vanquish Twitherym (UC)',
    [3706] = 'Subj.: Atkorkamuy (UC)',
    [3707] = 'Magic Bursts (UC)',
-- Unity (Yoran-Oran)
    -- Week 0
    [3668] = 'Club Weapon Skills (UC)',
    [3669] = 'Conflict: Giddeus (UC)',
    [3670] = 'Vanquish Efts (UC)',
    [3671] = 'Subj.: Herbage Hunter (UC)',
    [3672] = 'Heal Unity Allies (UC)',
    -- Week 1
    [3673] = 'Spoils (Rotten Meat) (UC)',
    [3674] = 'Conflict: Moh Gates (UC)',
    [3675] = 'Vanquish Antica (UC)',
    [3676] = 'Subj.: Antican Praefectus (UC)',
    [3677] = 'Cure Status Ailments (UC)',
    -- Week 2
    [3678] = 'Staff Weapon Skills (UC)',
    [3679] = 'Conflict: Toraimarai Canal (UC)',
    [3680] = 'Vanquish Couerls (UC)',
    [3681] = 'Subjugation: Ose (UC)',
    [3682] = 'Heal Unity Allies (UC)',
    -- Week 3
    [3683] = 'Spoils (Dullahan Armor) (UC)',
    [3684] = 'Conflict: Outer Ra\'Kaznar (UC)',
    [3685] = 'Vanquish Dullahan (UC)',
    [3686] = 'Subj.: Capricious Cassie (UC)',
    [3687] = 'Magic Bursts (UC)',
    -- Unity (Wanted 1)
    [817] = 'Subjugation: Hugemaw Harold (UC)',
    [818] = 'Subjugation: Bounding Belinda (UC)',
    [819] = 'Subjugation: Prickly Pitriv (UC)',
    [820] = 'Subjugation: Ironhorn Baldurno (UC)',
    [821] = 'Subjugation: Sleepy Mabel (UC)',
    [822] = 'Subjugation: Valkurm Imperator (UC)',
    [823] = 'Subjugation: Serpopard Ninlil (UC)',
    [824] = 'Subjugation: Abyssdiver (UC)',
    [825] = 'Subjugation: Intuila (UC)',
    [826] = 'Subjugation: Emperor Arthro (UC)',
    [827] = 'Subjugation: Orcfeltrap (UC)',
    [828] = 'Subjugation: Lumber Jill (UC)',
    [829] = 'Subjugation: Joyous Green (UC)',
    [830] = 'Subjugation: Strix (UC)',
    [831] = 'Subjugation: Warblade Beak (UC)',
    [832] = 'Subjugation: Arke (UC)',
    [833] = 'Subjugation: Largantua (UC)',
    [834] = 'Subjugation: Beist (UC)',
    [835] = 'Subjugation: Jester Malatrix (UC)',
    [836] = 'Subjugation: Cactrot Veloz (UC)',
    [837] = 'Subjugation: Woodland Mender (UC)',
    [854] = 'Subjugation: Sybaritic Samantha (UC)',
    [855] = 'Subj.: Keeper of Heiligtum (UC)',
    [856] = 'Subjugation: Douma Weapon (UC)',
    [857] = 'Subjugation: King Uropygid (UC)',
    [858] = 'Subjugation: Vedrfolnir (UC)',
    -- Unity (Wanted 2)
    [859] = 'Subjugation: Immanibugard (UC)',
    [860] = 'Subjugation: Tiyanak (UC)',
    [861] = 'Subjugation: Muut (UC)',
    [862] = 'Subjugation: Camahueto (UC)',
    [863] = 'Subjugation: Voso (UC)',
    [864] = 'Subjugation: Mephitas (UC)',
    [865] = 'Subjugation: Coca (UC)',
    [866] = 'Subjugation: Ayapec (UC)',
    [867] = 'Subjugation: Specter Worm (UC)',
    [868] = 'Subjugation: Azrael (UC)',
    [869] = 'Subjugation: Borealis (UC)',
    [891] = 'Subjugation: Garbage Gel (UC)',
    [892] = 'Subjugation: Bakunawa (UC)',
    [893] = 'Subjugation: Azure-tooth. Claw. (UC)',
    [898] = 'Subjugation: Centurio XX-I (UC)',
    [896] = 'Subjugation: Kub. Ja\'s Mhuufya (UC)',
    [899] = 'Subjugation: Vidmapire (UC)',
    [894] = 'Subjugation: Vermillion Fishfly (UC)',
    [895] = 'Subjugation: Volatile Cluster (UC)',
    [897] = 'Subjugation: Grand Grenade (UC)',
    [914] = 'Subjugation: Sovereign Behem. (UC)',
    [915] = 'Subjugation: Hidhaegg (UC)',
    [916] = 'Subjugation: Tolba (UC)',
    [918] = 'Subjugation: Carousing Celine (UC)',
    [919] = 'Subjugation: Glazemane (UC)',
    [920] = 'Subjugation: Bambrox (UC)',
    -- Unity (Wanted 3)
    [921] = 'Subjugation: Thu\'ban (UC)',
    [922] = 'Subjugation: Sarama (UC)',
    [923] = 'Subjugation: Shedu (UC)',
-- 'Vana\'versary'
    -- '15th Vana\'versary I'
    [2043] = 'Mythril Marathon',
    [3360] = 'Mythril Marathon (W)',
    [3361] = 'The Star of Tenshodo (W)',
    [3362] = 'Claret Carp (W)',
    [3363] = 'Gastro-revolution (W)', -- grape
    [3364] = 'Cure for What Ails You (W)',
    [3365] = 'Jinx (W)',
    [3366] = 'Stop Right There! (W)',
    [3367] = 'Signet, brb (W)',
    -- '15th Vana\'versary II'
    [2044] = 'Selbinary',
    [3368] = 'Selbinary (W)',
    [3369] = 'Mhauranian (W)',
    [3370] = 'Sunsand Rush (W)',
    [3371] = 'Gastro-revolution 2 (W)', -- apple pie
    [3372] = 'Crustacean Infusion (W)',
    [3373] = 'Yaaar! (W)',
    [3374] = 'Colorless (W)',
    [3375] = 'No Time to Be Sheepish (W)',
    -- '15th Vana\'versary III'
    [2045] = 'Papyrus Pursuer',
    [3376] = 'Papyrus Pursuer (W)',
    [3377] = 'Hide-and-Go-Seek (W)',
    [3378] = 'Full Deck (W)',
    [3379] = 'Unwavering Protector (W)',
    [3380] = 'Sit (W)',
    [3381] = 'Gastro-Revolution 3 (W)', -- roast mushroom
    [3382] = 'It\'s All a Blur (W)',
    [3383] = 'All That Glitters... (W)',
    -- '15th Vana\'versary IV'
    [2046] = 'Miratete 1',
    [3384] = 'Miratete 1 (W)',
    [3385] = 'Miratete 2 (W)',
    [3386] = 'A Strong Fellowship (W)',
    [3387] = 'Red Rover (W)',
    [3388] = '100 or Bust (W)',
    [3389] = 'Break the Blockade (W)',
    [3390] = 'Gastro-Revolution 4 (W)', -- ginger
    [3391] = 'Crustacean King (W)',
    -- '15th Vana\'versary V'
    [2047] = 'Say "Cheese"!',
    [3392] = 'Say "Cheese"! (W)',
    [3393] = 'Auction House Blues (W)',
    [3394] = 'Let Me Solo This (W)',
    [3395] = 'Ring Around the Rosie (W)',
    [3396] = 'The One True Path (W)',
    [3397] = '☆ (W)',
    [3398] = 'Gukumatz (W)',
    [3399] = 'See the Unseen (W)',
    -- '17th Vana\'versary'
    [4054] = '"True Love" Participation',
    [4055] = '"A Fond Farewell" Participation',
-- Other
    -- 'RoE Quests'
    [386] = 'Telepoint Pilgrimage',
    [387] = 'Culling the Darkness',
    [388] = 'Petals of Recollection',
    [527] = 'Grudge',
    [528] = 'Golden Rule',
    [529] = 'Impermanence',
    [530] = 'Panta Rhei',
    [531] = 'Leonine Excruciation',
    [532] = 'Shiver Me Timbers',
    [701] = 'Go With the Flow',
    [926] = 'Over Ninety-Thousand',
    [927] = 'Minnow Wrangler',
    [928] = 'A Thousand Cuts',
    [929] = 'Disappointment Valley',
    [930] = 'Remembrance of Flowers Past',
    -- 'RoE Quests 2'
    [955] = 'The Ygnas Directive 1',
    [956] = 'The Ygnas Directive 2',
    [957] = 'The Ygnas Directive 3',
    [958] = 'The Ygnas Directive 4',
    [959] = 'The Ygnas Directive 5',
    [960] = 'The Ygnas Directive 6',
    [961] = 'The Arciela Directive 1',
    -- 'RoE Quests 3'
    [964] = 'Quell Your Rage',
    [965] = 'Temper Your Arrogance',
    [966] = 'Stifle Your Envy',
    [967] = 'Overcome your Cowardice',
    [968] = 'Eliminate Your Apathy',
    [1444] = 'Filled to Capacity',
    [1445] = 'Over Capacity',
    [1446] = 'Way Over Capacity',
    -- 'Daily Objectives'
    [4082] = 'Vanquish Multiple Enemies (D)',
    [4083] = 'Buff Allies (D)',
    [4084] = 'Heal for 500+ HP (D)',
    -- 'Monthly Objectives'
        -- Pattern A
    [3779] = 'Gobbie Mystery Box (M)',
    [3782] = 'Chocobo Races (M)',
    [3785] = 'Walk of Echoes (M)',
        -- Pattern B
    [3780] = 'Grow and Harvest (M)',
    [3783] = 'Experience Chains (M)',
    [3786] = 'Wanted (M)',  -- the required mob changes I think
        -- Pattern C
    [3781] = 'Mog Garden Items (M)',
    [3784] = 'Coalition Assignments (M)',
    [3787] = 'Delve (M)',
        -- Common
    [3788] = 'High-Tier Mission Battlefields (M)', -- it's the same id for all 3 patterns
}
--[[ ============================================== ]]
--[[ ============================================== ]]
--[[ ============================================== ]]